---
title: "Week9-collab-doc"
format: html
editor: visual
---

Load Libraries

```{r}
library(tidyverse) #for data wrangling
library(ggeffects) #for model
library(lterdatasampler) #for data
library(here) #for file paths 
```

Reading in data

```{r}

data(pie_crab)

```

I will visualize this data

```{r}
ggplot(aes(x=latitude,y=size), data=pie_crab)+
  geom_point(color="orange")+
  labs(x = "Latitude",
       y = "Size")+
  theme_classic()
```

#### Writing model

```{r}

crab_model <- lm(size ~ latitude, # formula: response ~ predictor
                 data = pie_crab) # df

par(mfrow = c(2, 2)) # display plots in 2x2 grid 
plot(crab_model) # plot diagnostics 

```

#### Model diagnostic plot notes:

qq looks good, homogeneity looks good.

#### Run model and interpret 

```{r}
summary(crab_model) #look at model output
```

#### Summarize our Results:

slope: 0.485

y-int: -3.62 +/- 1.27

for each 1 degree increase in latitude, we expect crab size to increase by 0.485 +/- 0.034 mm.

Model Statistics: F(1,390) = 208.5, p \< 0.001, alpha = 0.05, R^2^ = 0.35
